### ISSUE TITLE
Version negotiation?

### ISSUE THREAD

**Issue by nex3** [sass/embedded-protocol#14]
Do we want to have some sort of version negotiation take place when the protocol is first connected? If we think we'll ever want this, specifying it early on will mean all implementations will support it at least well enough to say "no I don't support your protocol version". On the other hand, I expect most implementation distributions will be tightly-coupled enough that the embedder will always know which version of the compiler it's shipping (at least to within a semantic version range).

@strychnide What do you think?

**Comment by strychnide** [comment]
I guess we could have a "hello" message of some kind, not enforcing anything but just outputting informations and letting the implementations do what they want (maybe suggesting to implement the version check/other checks).

**Comment by nex3** [comment]
If we do this, I think we should at least enforce *some* kind of behavior so one endpoint doesn't just send something completely incomprehensible to the other. Something like, "if you don't get the handshake you expect, close the connection and emit an error".

**Comment by strychnide** [comment]
A handshake seems fine to me, some kind of "info" outbound message + an "everything ok" inbound message should be good enough, imo.

**Comment by nex3** [comment]
What would be in the "info" message? How should an endpoint react if the other's message isn't what it expects?

**Comment by strychnide** [comment]
Info message -> everything the host would want to check (atm only the version comes to mind but there may be more).
if a message isn't what it expects maybe we could use the ProtocolError we already defined?
