### ISSUE TITLE
Support including source contents in the SourceMap

### ISSUE THREAD

**Issue by Awjin** [sass/embedded-protocol#46]
Since the host doesn't have access to source contents, the protocol should allow the host to request that the compiler include source contents in the outputted source-map.

**Comment by johnfairh** [comment]
Hi @Awjin, can you say a bit more about why we wouldn't want `sass --embed-sources` equivalent supported here?  Does nobody actually use that style, or are you thinking that clients should do it themselves if needed by following the source map's URLs?

**Comment by stof** [comment]
Relying on clients to do it is a bad idea, as the client might not have access to the sources (which was part of the requirements when designing the error reporting for the new JS API btw)

**Comment by Awjin** [comment]
Hi folks, this issue was closed by accident.

**Comment by johnfairh** [comment]
Oh ok!  Thanks for checking.

**Comment by ntkme** [comment]
In fact, the recently introduced [new JS API](https://sass-lang.com/documentation/js-api/interfaces/Options) removed support for source contents. Does this mean dropping the feature for long term?

**Comment by stof** [comment]
@ntkme no. there is an open issue about adding it in the new API
