### ISSUE TITLE
Supported output styles

### ISSUE THREAD

**Issue by stof** [sass/embedded-protocol#47]
The protocol currently defines 4 output styles: https://github.com/sass/embedded-protocol/blob/3d0061a5451c4be1bafeb474f1ad912995328e8b/embedded_sass.proto#L57-L75

dart-sass only support expanded and compressed output. This means that dart-sass-embedded will replace `COMPACT` and `NESTED` with an `EXPANDED` output in the response. Given that dart-sass-embedded is the only implementation of the compiler side of this protocol (and it does not make sense to implement the compiler side of this protocol on top of libsass given it is deprecated), what is the reason to support `COMPACT` and `NESTED` in the protocol ?

If some host implementation wants to expose an API reproducing the API of an existing libsass wrapper for their language (to ease the migration), they could implement this conversion of `nested` and `compact` to `expanded` in their own API, before converting to the embedded protocol values.

**Comment by nex3** [comment]
Historically, when I was first writing the protocol the LibSass team expressed interest in implementing it, so I added this to support them. You're right that that's unlikely to happen now, so it's probably worth just removing those constants until we have an actual compiler implementation that demonstrably wants them to exist.
