### ISSUE TITLE
Clarifiy documentation for Value.CompilerFunction

### ISSUE THREAD

**Issue by larsgrefer** [sass/embedded-protocol#57]
I think the documentation for Value.CompilerFunction needs some improvement:

https://github.com/sass/embedded-protocol/blob/daadcf645ce3b666233654aa1318c55df96f04bb/embedded_sass.proto#L719-L721

The mentioned message type "InboundRequest.FunctionCallRequest" isn't defined anywhere.
Also "InboundMessage" which might be meant here, does not have a "FunctionCallRequest" either.

**Comment by Awjin** [comment]
Good catch. That message type was removed, so this documentation should be updated.
