### ISSUE TITLE
How to set load path

### ISSUE THREAD

**Issue by jcklie** [sass/embedded-protocol#70]
dart-sass allows setting the include path via https://sass-lang.com/documentation/cli/dart-sass#load-path . How can I do that with the sass embedded protocol?

**Comment by ntkme** [comment]
For each load path, you need to use an importer:
https://github.com/sass/embedded-protocol/blob/c23a2e226e29d7445893475b8e938f5ac9a65153/embedded_sass.proto#L67-L75

**Comment by jcklie** [comment]
Thanks!
