### ISSUE TITLE
Automatically create release tags

### ISSUE THREAD

**Issue by ntkme** [sass/embedded-protocol#78]
Tag `1.0.0-beta.15` is missing, which is used by the latest version of dart-sass-embedded.

The [changelog](https://github.com/sass/dart-sass-embedded/blob/main/CHANGELOG.md#100-beta12) of dart-sass-embedded says:
> Support version 1.0.0-beta.14 of the Sass embedded protocol

However, in reality it is `1.0.0-beta.15` not `1.0.0-beta.14`:

```
$ ./dart-sass-embedded --version
{
  "protocolVersion": "1.0.0-beta.15",
  "compilerVersion": "1.0.0-beta.12",
  "implementationVersion": "1.42.1",
  "implementationName": "Dart Sass",
  "id": 0
}
```

**Comment by ntkme** [comment]
The same kind of issue has happened once in the past (#71).

@nex3 Is it possible to a step to release process so that: whenever a new version of dart-sass-embedded is released, ensures the protocol version being used is always tagged?

**Comment by nex3** [comment]
That's a good question. I wonder if it would make more sense for this repo to just automatically tag commits that update the `VERSION` file, since it's easy to verify...
