### ISSUE TITLE
Multiple imports from one import statement

### ISSUE THREAD

**Issue by bolandrm** [sass/embedded-protocol#82]
From what I can tell in the specification, it doesn't look like it's possible to map one `import` statement to multiple results.  With libsass, we can implement a custom importer that takes something like this:

```
@import "globbed/**/*";
```

and returns a list of imported files  (i.e. `sass_make_import_list`).

I'm wondering if it might be possible to have a `CanonicalizeResponse` include an array of URLs rather than strictly only one.  Otherwise, is there another way to implement this functionality?

**Comment by ntkme** [comment]
You can implement a [user importer](https://github.com/sass/embedded-protocol/blob/d2e5b4665e4479defb142c17562e7e13896d118b/embedded_sass.proto#L77-L82) like:

1. In `CanonicalizeReponse` it basically does nothing: e.g. `globbed/**/*` canonicalize to `globbed/**/*`.
2. In `ImportResponse` it returns a [content](https://github.com/sass/embedded-protocol/blob/d2e5b4665e4479defb142c17562e7e13896d118b/embedded_sass.proto#L158) being a new scss stylesheet only containing multiple `@import` statements to import resolved all files.

The idea here is to treat `globbed/**/*` as a scss file that virtually exists, which imports rest of files you want.

**Comment by nex3** [comment]
We explicitly discourage globbed imports. CSS is a very order-sensitive language, and globs don't provide a clear or consistent ordering among files.
